package com.householdfinance.finance.application.service;import com.householdfinance.finance.application.port.out.*;import com.householdfinance.finance.application.port.in.*;import com.householdfinance.finance.domain.*;import java.time.*;import java.util.*;import org.springframework.transaction.annotation.Transactional;
abstract class Support{protected final FinanceRepository r;Support(FinanceRepository r){this.r=r;}protected Household h(HouseholdId i){return r.household(i).orElseThrow(()->new DomainException("Household not found"));}protected Household member(UUID u,HouseholdId i){var h=h(i);h.requireActiveMember(u);return h;}protected FinancialAccount a(AccountId i){return r.account(i).orElseThrow(()->new DomainException("Account not found"));}
/** Fetches the account under a pessimistic write lock so concurrent income/expense/transfer operations on the same account are serialized by the database instead of racing on the in-memory balance. Must only be called inside a @Transactional method. */
protected FinancialAccount lockedAccount(AccountId i){return r.lockAccount(i).orElseThrow(()->new DomainException("Account not found"));}}
class HouseholdService extends Support implements HouseholdUseCase{HouseholdService(FinanceRepository r){super(r);}public Household create(UUID u,String n){return r.save(Household.create(n,u,Instant.now()));}public Household get(UUID u,HouseholdId i){return member(u,i);}public void rename(UUID u,HouseholdId i,String n){var h=member(u,i);h.rename(n,u,Instant.now());r.save(h);}public void addMember(UUID u,HouseholdId i,UUID m,MemberRole role){var h=member(u,i);h.requireAdmin(u);h.addMember(u,m,role,Instant.now());r.save(h);}public void removeMember(UUID u,HouseholdId i,UUID m){var h=member(u,i);h.removeMember(u,m,Instant.now());r.save(h);}}
class AccountService extends Support implements AccountUseCase{AccountService(FinanceRepository r){super(r);}public FinancialAccount open(UUID u,HouseholdId h,String n,AccountType t,Money b){member(u,h);return r.save(FinancialAccount.open(h,n,t,b,Instant.now()));}public List<FinancialAccount> list(UUID u,HouseholdId h){member(u,h);return r.accounts(h);}}
class TransactionService extends Support implements TransactionUseCase{TransactionService(FinanceRepository r){super(r);}
@Transactional
public Transaction record(UUID u,HouseholdId h,AccountId id,UUID c,TransactionType t,Money m,Instant at,String d){member(u,h);var a=lockedAccount(id);if(!a.householdId().equals(h))throw new DomainException("Wrong household");var tx=Transaction.record(h,id,c,t,m,at,d);if(t==TransactionType.INCOME)a.credit(m,Instant.now());else a.debit(m,Instant.now());r.save(a);return r.save(tx);}
@Transactional
public Transaction transfer(UUID u,HouseholdId h,AccountId f,AccountId to,Money m,Instant at,String d){member(u,h);if(f.value().equals(to.value()))throw new DomainException("Invalid transfer accounts");
// Lock both accounts in a deterministic order (ascending UUID) to prevent lock-ordering deadlocks between concurrent transfers that touch the same pair of accounts in opposite directions.
boolean fFirst=f.value().compareTo(to.value())<0;var firstLocked=lockedAccount(fFirst?f:to);var secondLocked=lockedAccount(fFirst?to:f);var x=fFirst?firstLocked:secondLocked;var y=fFirst?secondLocked:firstLocked;
if(!x.householdId().equals(h)||!y.householdId().equals(h)||!x.currency().equals(y.currency()))throw new DomainException("Invalid transfer accounts");x.debit(m,Instant.now());y.credit(m,Instant.now());r.save(x);r.save(y);return r.save(Transaction.transfer(h,f,to,m,at,d));}
public List<Transaction> list(UUID u,HouseholdId h){member(u,h);return r.transactions(h);}}
class BillService extends Support implements BillUseCase{BillService(FinanceRepository r){super(r);}@Transactional public HouseholdBill create(UUID u,HouseholdId h,String n,Money a,LocalDate d){member(u,h);return r.save(HouseholdBill.create(h,n,a,d));}@Transactional public BillOccurrence occurrence(UUID u,BillId b,LocalDate d){var bill=r.bill(b).orElseThrow(()->new DomainException("Bill not found"));member(u,bill.householdId());if(r.occurrences(b).stream().anyMatch(o->o.dueDate().equals(d)))throw new DomainException("Bill occurrence already exists");return r.save(BillOccurrence.create(b,d));}@Transactional public BillOccurrence pay(UUID u,OccurrenceId i,AccountId accountId,String description){var o=r.occurrence(i).orElseThrow(()->new DomainException("Occurrence not found"));var b=r.bill(o.billId()).orElseThrow(()->new DomainException("Bill not found"));member(u,b.householdId());var account=lockedAccount(accountId);if(!account.householdId().equals(b.householdId()))throw new DomainException("Wrong household");var transaction=Transaction.record(b.householdId(),accountId,null,TransactionType.BILL_PAYMENT,b.amount(),Instant.now(),description==null?b.name():description);account.debit(b.amount(),Instant.now());o.markPaid(transaction.id());r.save(account);r.save(transaction);return r.save(o);}public List<HouseholdBill> list(UUID u,HouseholdId h){member(u,h);return r.bills(h);}}
class CreditCardService extends Support implements CreditCardUseCase{CreditCardService(FinanceRepository r){super(r);}public CreditCard issue(UUID u,HouseholdId h,String n,Money l){member(u,h);return r.save(CreditCard.issue(h,n,l));}public List<CreditCard> list(UUID u,HouseholdId h){member(u,h);return r.cards(h);}}
class CategoryService extends Support implements CategoryUseCase{CategoryService(FinanceRepository r){super(r);}public Category create(UUID u,HouseholdId h,String n){member(u,h);return r.save(Category.create(h,n));}public List<Category> list(UUID u,HouseholdId h){member(u,h);return r.categories(h);}}
class BudgetService extends Support implements BudgetUseCase{BudgetService(FinanceRepository r){super(r);}@Transactional public Budget create(UUID u,HouseholdId h,CategoryId c,Money l,BudgetPeriod p,LocalDate s,LocalDate e){member(u,h);return r.save(Budget.create(h,c,l,p,s,e));}public List<Budget> list(UUID u,HouseholdId h){member(u,h);return r.budgets(h);}}
class ReportService extends Support implements ReportUseCase{ReportService(FinanceRepository r){super(r);}public Report summary(UUID u,HouseholdId h,LocalDate f,LocalDate t){member(u,h);Money in=null;Money out=null;long n=0;for(var x:r.transactions(h)){var d=x.occurredAt().atZone(java.time.ZoneOffset.UTC).toLocalDate();if(!d.isBefore(f)&&!d.isAfter(t)){n++;if(x.type()==TransactionType.INCOME)in=in==null?x.amount():in.add(x.amount());if(x.type()==TransactionType.EXPENSE)out=out==null?x.amount():out.add(x.amount());}}var cur=in!=null?in.currency():out!=null?out.currency():Currency.getInstance("USD");if(in==null)in=Money.zero(cur);if(out==null)out=Money.zero(cur);return new Report(in,out,in.subtract(out),n);}}
